services:
  - type: web
    name: phishing-detector
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install numpy==1.21.6 pandas==1.5.3 scikit-learn==1.1.3 --only-binary=:all:
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
